services:
  bash:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - LVSC_ROOT_PATH=/lvsc_data
    - SUNNYBROOK_ROOT_PATH=/sunnybrook_data
    image: vuptran_cardiac_segmentation:latest
    volumes:
    - .:/project
    - /home/grihabor/Desktop/sunnybrook:/sunnybrook_data
    - nvidia_driver_384.90:/usr/local/nvidia:ro
  train_sunnybrook:
    command: python train_sunnybrook.py i 0
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    extends:
      file: docker-compose.yml
      service: bash
    volumes:
    - nvidia_driver_384.90:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.90:
    external: true
